name: hero_text
description: Hero Effect for your texts.
version: 0.0.1
homepage:
  https://github:com/sshadkany/HeroText
environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
